apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      name: client
  template:
    metadata:
      labels:
        name: client
    spec:
      containers:
      - name: client
        image: tomwilkie/client
        imagePullPolicy: IfNotPresent
        args:
          - -target=frontend.default.svc.cluster.local
