apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      name: frontend
  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers:
      - name: frontend
        image: tomwilkie/frontend-k8s
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
