apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
spec:
  replicas: 1
  selector:
    matchLabels:
      name: search
  template:
    metadata:
      labels:
        name: search
    spec:
      containers:
      - name: search
        image: tomwilkie/searchapp
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        args:
          - -addr=:80
          - -target=http://elasticsearch.default.svc.cluster.local:9200

